export const GET_DOWNLOAD_SPEED = 'GET_DOWNLOAD_SPEED';
export const GET_UPLOAD_SPEED = 'GET_UPLOAD_SPEED';
export const RESET_ACTION = 'RESET_ACTION';
export const CHANGE_DOWNLOAD_STATE = 'CHANGE_DOWNLOAD_STATE';
export const CHANGE_UPLOAD_STATE = 'CHANGE_UPLOAD_STATE';
export const ADD_TO_HISTORY_LIST = 'ADD_TO_HISTORY_LIST';
export const REMOVE_FROM_HISTORY_LIST = 'REMOVE_FROM_HISTORY_LIST';
