export const GET_DOWNLOAD_SPEED = 'GET_DOWNLOAD_SPEED';
export const GET_UPLOAD_SPEED = 'GET_UPLOAD_SPEED';
export const RESET_ACTION = 'RESET_ACTION';
export const CHNAGE_DOWNLOAD_STATE = 'CHNAGE_DOWNLOAD_STATE';
export const CHNAGE_UPLOAD_STATE = 'CHNAGE_UPLOAD_STATE';
